export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';

export const SEARCH_ALBUMS_SUCCESS = 'SEARCH_ALBUMS_SUCCESS';

export const PAGINATE_ALBUMS_SUCCESS = 'SEARCH_ALBUMS_SUCCESS';
