name: tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Install node modules
        shell: sh
        run: npm ci
      - name: Running lint
        shell: sh
        run: npm run lint
      - name: Running tests
        shell: sh
        run: npm test
